In [17]:
import pandas as pd

df = pd.read_csv(r"/Users/admin/Documents/dev/algobetting/infra/data/collectors/whoscored/events_202526.csv")
df['team'] = df['homeTeam'].where(df['h_a'] == 'h', df['awayTeam'])

df

/var/folders/7c/dkh0wxt56g39m3h9nmfq79mc0000gn/T/ipykernel_45053/139440268.py:3: DtypeWarning: Columns (262) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"/Users/admin/Documents/dev/algobetting/infra/data/collectors/whoscored/events_202526.csv")

,Unnamed: 0,id,eventId,minute,second,teamId,h_a,x,y,expandedMinute,...,throwIn,subOn,subOff,defensiveThird,midThird,finalThird,pos,EPV,isOwnGoal,team
0,0,2.835141e+09,3,0,0.0,26,h,0.0,0.0,0,...,False,False,False,False,False,False,False,NaN,NaN,Liverpool
1,1,2.835141e+09,3,0,0.0,183,a,0.0,0.0,0,...,False,False,False,False,False,False,False,NaN,NaN,Bournemouth
2,2,2.835141e+09,4,0,0.0,26,h,49.9,50.2,0,...,False,False,False,True,False,False,True,-0.0034,NaN,Liverpool
3,3,2.835141e+09,5,0,3.0,26,h,29.9,60.3,0,...,False,False,False,False,False,True,True,NaN,NaN,Liverpool
4,4,2.835240e+09,749,0,5.0,183,a,24.9,70.3,0,...,False,False,False,False,False,False,False,NaN,NaN,Bournemouth
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104874,1547,2.856553e+09,924,96,50.0,211,a,0.0,0.0,99,...,False,False,False,False,False,False,False,NaN,NaN,Brighton
104875,1548,2.856553e+09,778,0,0.0,161,h,0.0,0.0,9,...,False,False,False,False,False,False,False,NaN,NaN,Wolves
104876,1549,2.856554e+09,926,0,0.0,211,a,0.0,0.0,9,...,False,False,False,False,False,False,False,NaN,NaN,Brighton
104877,1550,2.856324e+09,2,0,0.0,161,h,0.0,0.0,0,...,False,False,False,False,False,False,False,NaN,NaN,Wolves
104878,1551,2.856324e+09,2,0,0.0,211,a,0.0,0.0,0,...,False,False,False,False,False,False,False,NaN,NaN,Brighton

In [26]:
for col in df.columns:
    print(col)

Unnamed: 0
id
eventId
minute
second
teamId
h_a
x
y
expandedMinute
period
type
outcomeType
qualifiers
satisfiedEventsTypes
isTouch
matchId
startDate
startTime
score
ftScore
htScore
etScore
venueName
maxMinute
homeTeam
awayTeam
playerId
playerName
endX
endY
relatedEventId
relatedPlayerId
blockedX
blockedY
goalMouthZ
goalMouthY
isShot
cardType
isGoal
shotBodyType
situation
shotSixYardBox
shotPenaltyArea
shotOboxTotal
shotOpenPlay
shotCounter
shotSetPiece
shotDirectCorner
shotOffTarget
shotOnPost
shotOnTarget
shotsTotal
shotBlocked
shotRightFoot
shotLeftFoot
shotHead
shotObp
goalSixYardBox
goalPenaltyArea
goalObox
goalOpenPlay
goalCounter
goalSetPiece
penaltyScored
goalOwn
goalNormal
goalRightFoot
goalLeftFoot
goalHead
goalObp
shortPassInaccurate
shortPassAccurate
passCorner
passCornerAccurate
passCornerInaccurate
passFreekick
passBack
passForward
passLeft
passRight
keyPassLong
keyPassShort
keyPassCross
keyPassCorner
keyPassThroughball
keyPassFreekick
keyPassThrowin
keyPassOther
assistCross
assistCorner
assistThroughball
assistFreekick
assistThrowin
assistOther
dribbleLost
dribbleWon
challengeLost
interceptionWon
clearanceHead
outfielderBlock
passCrossBlockedDefensive
outfielderBlockedPass
offsideGiven
offsideProvoked
foulGiven
foulCommitted
yellowCard
voidYellowCard
secondYellow
redCard
turnover
dispossessed
saveLowLeft
saveHighLeft
saveLowCentre
saveHighCentre
saveLowRight
saveHighRight
saveHands
saveFeet
saveObp
saveSixYardBox
savePenaltyArea
saveObox
keeperDivingSave
standingSave
closeMissHigh
closeMissHighLeft
closeMissHighRight
closeMissLeft
closeMissRight
shotOffTargetInsideBox
touches
assist
ballRecovery
clearanceEffective
clearanceTotal
clearanceOffTheLine
dribbleLastman
errorLeadsToGoal
errorLeadsToShot
intentionalAssist
interceptionAll
interceptionIntheBox
keeperClaimHighLost
keeperClaimHighWon
keeperClaimLost
keeperClaimWon
keeperOneToOneWon
parriedDanger
parriedSafe
collected
keeperPenaltySaved
keeperSaveInTheBox
keeperSaveTotal
keeperSmother
keeperSweeperLost
keeperMissed
passAccurate
passBackZoneInaccurate
passForwardZoneAccurate
passInaccurate
passAccuracy
cornerAwarded
passKey
passChipped
passCrossAccurate
passCrossInaccurate
passLongBallAccurate
passLongBallInaccurate
passThroughBallAccurate
passThroughBallInaccurate
passThroughBallInacurate
passFreekickAccurate
passFreekickInaccurate
penaltyConceded
penaltyMissed
penaltyWon
passRightFoot
passLeftFoot
passHead
sixYardBlock
tackleLastMan
tackleLost
tackleWon
cleanSheetGK
cleanSheetDL
cleanSheetDC
cleanSheetDR
cleanSheetDML
cleanSheetDMC
cleanSheetDMR
cleanSheetML
cleanSheetMC
cleanSheetMR
cleanSheetAML
cleanSheetAMC
cleanSheetAMR
cleanSheetFWL
cleanSheetFW
cleanSheetFWR
cleanSheetSub
goalConcededByTeamGK
goalConcededByTeamDL
goalConcededByTeamDC
goalConcededByTeamDR
goalConcededByTeamDML
goalConcededByTeamDMC
goalConcededByTeamDMR
goalConcededByTeamML
goalConcededByTeamMC
goalConcededByTeamMR
goalConcededByTeamAML
goalConcededByTeamAMC
goalConcededByTeamAMR
goalConcededByTeamFWL
goalConcededByTeamFW
goalConcededByTeamFWR
goalConcededByTeamSub
goalConcededOutsideBoxGoalkeeper
goalScoredByTeamGK
goalScoredByTeamDL
goalScoredByTeamDC
goalScoredByTeamDR
goalScoredByTeamDML
goalScoredByTeamDMC
goalScoredByTeamDMR
goalScoredByTeamML
goalScoredByTeamMC
goalScoredByTeamMR
goalScoredByTeamAML
goalScoredByTeamAMC
goalScoredByTeamAMR
goalScoredByTeamFWL
goalScoredByTeamFW
goalScoredByTeamFWR
goalScoredByTeamSub
aerialSuccess
duelAerialWon
duelAerialLost
offensiveDuel
defensiveDuel
bigChanceMissed
bigChanceScored
bigChanceCreated
overrun
successfulFinalThirdPasses
punches
penaltyShootoutScored
penaltyShootoutMissedOffTarget
penaltyShootoutSaved
penaltyShootoutSavedGK
penaltyShootoutConcededGK
throwIn
subOn
subOff
defensiveThird
midThird
finalThird
pos
EPV
isOwnGoal
team

In [37]:
df_filtered = df[["matchId", "startDate", "minute", "second", "team", 'h_a', "x", "y", "type", "isTouch", "passAccurate", "passInaccurate", "EPV"]]
df_filtered = df_filtered[df_filtered["type"] == "Pass"]
df_filtered['startDate'] = pd.to_datetime(df_filtered['startDate'])

df_filtered[df_filtered['team'] == 'Arsenal']

,matchId,startDate,minute,second,team,h_a,x,y,type,isTouch,passAccurate,passInaccurate,EPV
11536,1903125,2025-08-17,0,0.0,Arsenal,a,50.1,50.1,Pass,True,True,False,-0.0047
11537,1903125,2025-08-17,0,3.0,Arsenal,a,27.1,52.2,Pass,True,False,True,NaN
11544,1903125,2025-08-17,0,36.0,Arsenal,a,93.4,100.0,Pass,True,False,False,NaN
11559,1903125,2025-08-17,1,26.0,Arsenal,a,23.9,41.5,Pass,True,True,False,-0.0007
11562,1903125,2025-08-17,1,42.0,Arsenal,a,9.4,56.9,Pass,True,False,False,0.0002
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95515,1903165,2025-10-04,96,49.0,Arsenal,h,80.4,10.9,Pass,True,True,False,0.0014
95516,1903165,2025-10-04,96,50.0,Arsenal,h,83.8,3.7,Pass,True,True,False,-0.0014
95517,1903165,2025-10-04,96,51.0,Arsenal,h,80.4,8.5,Pass,True,True,False,-0.0024
95518,1903165,2025-10-04,96,52.0,Arsenal,h,78.3,1.6,Pass,True,True,False,0.0021
95519,1903165,2025-10-04,96,53.0,Arsenal,h,82.0,2.2,Pass,True,False,True,NaN

In [39]:
epv = df_filtered.groupby(["matchId", "team", 'startDate']).agg({
    "EPV": "sum"
}).reset_index()

epv[epv["matchId"] == 1903165]

    matchId      team  startDate     EPV
96  1903165   Arsenal 2025-10-04  1.6442
97  1903165  West Ham 2025-10-04  0.9297

In [41]:
epv['season'] = '2025-26'
epv['division'] = 'Premier_League'

epv

     matchId               team  startDate     EPV   season        division
0    1903117        Bournemouth 2025-08-15  1.1574  2025-26  Premier_League
1    1903117          Liverpool 2025-08-15  1.6172  2025-26  Premier_League
2    1903118        Aston Villa 2025-08-16  0.6499  2025-26  Premier_League
3    1903118          Newcastle 2025-08-16  1.0343  2025-26  Premier_League
4    1903119           Brighton 2025-08-16  1.1531  2025-26  Premier_League
..       ...                ...        ...     ...      ...             ...
135  1903185    Manchester City 2025-09-27  1.2398  2025-26  Premier_League
136  1903186            Arsenal 2025-09-28  1.9964  2025-26  Premier_League
137  1903186          Newcastle 2025-09-28  0.9471  2025-26  Premier_League
138  1903188  Nottingham Forest 2025-09-27  1.7654  2025-26  Premier_League
139  1903188         Sunderland 2025-09-27  0.7231  2025-26  Premier_League

[140 rows x 6 columns]

In [42]:
epv['team'].unique()

array(['Bournemouth', 'Liverpool', 'Aston Villa', 'Newcastle', 'Brighton',
       'Fulham', 'Brentford', 'Nottingham Forest', 'Sunderland',
       'West Ham', 'Burnley', 'Tottenham', 'Manchester City', 'Wolves',
       'Chelsea', 'Crystal Palace', 'Arsenal', 'Manchester United',
       'Everton', 'Leeds'], dtype=object)

In [44]:
team_mapping = {
    'Nottingham Forest': 'Nottm Forest',
    'Manchester City': 'Man City',
    'Manchester United': 'Man United',
}

epv['team'] = epv['team'].replace(team_mapping)
epv['team'].unique()

array(['Bournemouth', 'Liverpool', 'Aston Villa', 'Newcastle', 'Brighton',
       'Fulham', 'Brentford', 'Nottm Forest', 'Sunderland', 'West Ham',
       'Burnley', 'Tottenham', 'Man City', 'Wolves', 'Chelsea',
       'Crystal Palace', 'Arsenal', 'Man United', 'Everton', 'Leeds'],
      dtype=object)